name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # মূল ব্রাঞ্চ (প্রয়োজনে পরিবর্তন করুন)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          script: "worker.js"  # Worker স্ক্রিপ্টের নাম
